compiler-check: newer-minor
resolver: lts-11.0
require-stack-version: ! '>=1.6'

flags:
  rfc:
      development: true
  wai-cli:
      tls: false
  postgresql-typed:
      hdbc: false
  base:
      integer-gmp: true
  http-api-data:
      use-text-show: true
  aeson:
      cffi: true
      fast: false
  cryptonite:
      support_pclmuldq: true
  zlib:
      non-blocking-ffi: true
  tls:
      compat: false

extra-package-dbs: []
packages:
- .
extra-deps:  
- simple-logger-0.0.4
- time-units-1.0.0
- url-2.1.3
- miso-0.15.0.0
