compiler-check: newer-minor
resolver: nightly-2018-03-10
require-stack-version: ! '>=1.6'

flags:
  rfc:
    development: true
  wai-cli:
    tls: false
  postgresql-typed:
    hdbc: false

extra-package-dbs: []
packages:
- .
extra-deps: 
- classy-prelude-1.4.0
- lens-4.16
- servant-0.13
- servant-client-0.13
- servant-client-core-0.13
- servant-docs-0.11.2
- servant-server-0.13
- servant-swagger-1.1.5
- simple-logger-0.0.4
- time-units-1.0.0
- http-types-0.12.1
