compiler-check: newer-minor
resolver: lts-11.16
require-stack-version: ! '>=1.6'

flags:
  rfc-prelude:
      production: false
  rfc-env:
      production: false
  rfc-miso:
      production: false
  rfc-redis:
      production: false
  rfc-psql:
      production: false
  rfc-http-client:
      production: false
  rfc-servant:
      production: false
  wai-cli:
      tls: false
  postgresql-typed:
      hdbc: false
  postgresql-binary:
      hdbc: false
  base:
      integer-gmp: true
  http-api-data:
      use-text-show: true
  aeson:
      cffi: true
      fast: false
      developer: false
      bytestring-builder: false
  cryptonite:
      support_pclmuldq: true
  zlib:
      non-blocking-ffi: true
  tls:
      compat: false
  miso:
    examples: false
    tests: false
  wai-cli:
    tls: false

extra-package-dbs: []
packages:
- './rfc-prelude'
- './rfc-env'
- './rfc-miso'
- './rfc-redis'
- './rfc-psql'
- './rfc-http-client'
- './rfc-servant'
- './rfc-wai'
extra-deps:  
- miso-0.20.1.0
- time-units-1.0.0

