name: rfc-miso
version: 0.0.0.1
synopsis: Miso extensions provided by the Robert Fischer Commons.
description: >
  Provides various experimental extensions for the Miso front end development framework.
category: Web
github: RobertFischer/rfc/rfc-miso
author: Robert Fischer
license: MIT

_common: !include package.common.yaml

<<: *defaults

dependencies:
  - rfc-prelude 
  - miso >= 0.20
  - base >= 4 && < 5
  - text >= 1.2
  - mono-traversable >= 1.0

when:
  condition: impl(ghcjs)
  dependencies:
    - rfc-ghcjs
