#!/bin/bash -exu

cd `dirname $0`/..

stack dot --stack-yaml=./stack.ghcjs.yaml --prune base,lens,array,bytestring,mtl,template-haskell,aeson,unordered-containers,classy-prelude,containers,exceptions,stm,lifted-base,async,monad-control,text,deepseq,transformers,rts,time,binary,ghc-prim,integer-gmp,primitive,hashable,vector,transformers-compat,scientific,base-compat --external --no-include-base | tee dependencies.dot | dot -Tsvg -o dependencies.svg
