#!/bin/bash -exu

cd `dirname $0`/..

stack build --stack-yaml=./stack.ghcjs.yaml --fast 
stack build --stack-yaml=./stack.ghcjs.yaml --haddock --haddock-deps --fast

stack build --fast 
stack build --haddock --haddock-deps --fast
