#!/bin/bash -exu

cd `dirname $0`/..

stack build --stack-yaml=./stack.ghcjs.yaml --fast
stack build --fast

stack clean 
stack clean --stack-yaml=./stack.ghcjs.yaml 
stack build --stack-yaml=./stack.ghcjs.yaml --fast

stack clean 
stack clean --stack-yaml=./stack.ghcjs.yaml 
stack build --fast
