name: rfc-prelude
version: 0.0.0.1
synopsis: The Prelude from the Robert Fischer Commons.
description: >
  A Prelude deriving from @Classy-Prelude@ which provides additional useful bits of 
  functionality and convenient names.
category: prelude
github: RobertFischer/rfc/rfc-prelude
author: Robert Fischer
license: MIT

_common: !include "../package.common.yaml"

<<: *defaults

dependencies:
  - classy-prelude >= 1.4
  - lens >= 4.16 
  - bifunctors >= 5.5
  - transformers >= 0.5
  - monad-control >= 1.0
  - data-default >= 0.7
  - unliftio >= 0.2
  - time >= 1.8
  - bytestring >= 0.10
  - text >= 1.2
  - text-conversions >= 0.3
  - network-uri >= 2.6
  - time-units >= 1.0
  - tuple >= 0.3
  - uuid-types >= 1.0
  - base >= 4.10
  - integer-logarithms >= 1.0
  - aeson >= 1.4
  - http-api-data >= 0.3
  - containers >= 0.5
